### PR TITLE
Reading commands from standard input: now supporting every command

### PR DESCRIPTION
**Pull request by technillogue**
Alright, this is my latest attempt at #583 #446 #87 etc. My trick here is having the input be namespaces that would be parsed from CLI options, and then using `getCommand` the same way Main.java does it. This approach avoids the issue DBus had with feature parity. 

NamespaceDefaultingToFalse means you can avoid NullPointerException without having to set every flag. There might be a better name for this command.

### CODE REVIEW

**Comment by technillogue** [comment]
@AsamK, any thoughts about this? does this go against part of signal-cli's design philosophy?

**Comment by AsamK** [comment]
I like the approach.
My initial idea would be to restrict this to commands, that have json output and to maybe wrap the command output in a response object to distinguish them from incoming messages. That would probably require some refactoring for the command classes.
I will have a closer look next week.

**Comment by technillogue** [comment]
How about this? Re-parsing the JSON is a little hacky, but a much smaller diff than refactoring every command. 

For which commands without JSON output would this be an issue? Although probably not super useful this does allow for keeping plain-text output by default, or specifying output format per command. 

Come to think of it, you could even do something like:

```if (inJson) {
    Map<String, Object> commandMap = jsonProcessor.readValue(input, inputType);
} else {
    var parser = App.buildArgumentParser();
    var commandMap = parser.parseArgsOrFail(input.split(" "));.
}
```

**Comment by technillogue** [comment]
For which commands without JSON output would this be an issue? This does allow for keeping plain-text output by default, or specifying output format per command. 

Come to think of it, you could even do something like:

```if (inJson) {
    Map<String, Object> commandMap = jsonProcessor.readValue(input, inputType);
} else {
    var parser = App.buildArgumentParser();
    var commandMap = parser.parseArgsOrFail(input.split(" "));.
}
```
Probably not especially useful, though.

**Comment by AsamK** [comment]
Thanks again for the PR.
I've now implemented this with a similar approach and an API based on JSON-RPC, see #679

**Pull request closed without merging**
