### PR TITLE
extend DBus signals for DbusAttachments 

### PR DESCRIPTION
**Pull request by johnfreed**
implement several subcommands for use by Dbus clients
    +    void setExpirationTimer(String number, int expiration) 
    +    boolean isRegistered(String number)
    +    List<Boolean> isRegistered(List<String> numbers)
    +    String getObjectPath()
    +    List<String> listDevices()
    +    void updateAccount()
    +    List<String> listIdentity(String number)

### CODE REVIEW

**Comment by johnfreed** [comment]
This pull request is to address #671 #316 #658 and #491, in particular addressing the issues raised by @AsamK in #658. 

I see two possible approaches to extending the DBus interface to allow user programs to receive mentions and the full metadata surrounding an attachment. This also paves the way to implementing quotes and quoted attachments.

1) change the API. This would "bite the bullet" and basically say to any existing user that the interface was always experimental, and now it has changed. If you want your program to work, change it.

2) add to the API but maintain backward compatibility. This has the downside of some code repetition. This is the approach I take in this pull request. It maintains full backward compatibility with what I will call the legacy API while implementing a version 2. 

This PR does that by introducing two new data structures (DBus requires a `Struct` because the order of the data matters, which Java does not provide by default). The new data types are `DbusMention` (created by @0b11001111) and `DbusAttachment`.

It also introduces two new signals, `MessageReceivedV2` and `SyncMessageReceivedV2`.

The new signals provide the new data structures to the user program, while the existing signals, `MessageReceived` and `SyncMessageReceived`, continue to provide the old data types (with no information about mentions or attachment metadata).

As a result, for each message received, two signals will be emitted: the legacy signal and the V2 signal. Existing (old-style) programs will not see the V2 signal, and so nothing will break. New programs can ignore the legacy signal and process the enhanced data.

Since this is a DBus protocol, it runs on a local machine, so the environment is known. However, this approach allows extension to non-local machines, where it will not be known whether `signal-cli` is using the old or new API. The sample program, `signalmail`, demonstrates this in action, where it accepts either legacy or V2 signals and processes them appropriately. (If a V2 signal is received, then a legacy signal will always also be received, so it has logic to avoid duplicate processing of messages. If only a legacy signal is received, that means the server has an old version of signal-cli and the sample program responds accordingly.) 

The `signalmail` program also demonstrates decoding of a mention. 

As a side benefit, this PR also permits sending the contents of an arbitrary URL (not just the contents of a local file) as an attachment for both the legacy and V2 API.

**Comment by johnfreed** [comment]
This pull request is to address #671 #316 #658 and #491, in particular addressing the issues raised by @AsamK in #658. 

I see two possible approaches to extending the DBus interface to allow user programs to receive mentions and the full metadata surrounding an attachment. This also paves the way to implementing quotes and quoted attachments.

1) change the API. This would "bite the bullet" and basically say to any existing user that the interface was always experimental, and now it has changed. If you want your program to work, change it.

2) add to the API but maintain backward compatibility. This has the downside of some code repetition. This is the approach I take in this pull request. It maintains full backward compatibility with what I will call the legacy API while implementing a version 2. 

This PR does that by introducing two new data structures (DBus requires a `Struct` because the order of the data matters, which Java does not provide by default). The new data types are `DbusMention` (created by @0b11001111) and `DbusAttachment`.

It also introduces two new signals, `MessageReceivedV2` and `SyncMessageReceivedV2`.

The new signals provide the new data structures to the user program, while the existing signals, `MessageReceived` and `SyncMessageReceived`, continue to provide the old data types (with no information about mentions or attachment metadata).

As a result, for each message received, two signals will be emitted: the legacy signal and the V2 signal. Existing (old-style) programs will not see the V2 signal, and so nothing will break. New programs can ignore the legacy signal and process the enhanced data.

Since this is a DBus protocol, it runs on a local machine, so the environment is known. However, this approach allows extension to non-local machines, where it will not be known whether `signal-cli` is using the old or new API. The sample program, `signalmail`, demonstrates this in action, where it accepts either legacy or V2 signals and processes them appropriately. (If a V2 signal is received, then a legacy signal will always also be received, so it has logic to avoid duplicate processing of messages. If only a legacy signal is received, that means the server has an old version of signal-cli and the sample program responds accordingly.) 

The `signalmail` program also demonstrates decoding of a mention. 

As a side benefit, this PR also permits sending the contents of an arbitrary URL (not just the contents of a local file) as an attachment for both the legacy and V2 API.

====================

Note that this pull requests also includes some older commits implementing various DBus methods. These can be cherry-picked.

**Comment by 0b11001111** [comment]
Fantastic! I'll check it out :)

**Comment by johnfreed** [comment]
Closing this to break it into chunks as requested in CONTRIBUTING.md

**Pull request closed without merging**
