### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by larsborn**
I use a server monitoring solution (Zabbix) and wanted to use signal-cli for notifications. The monitoring solutions can call external scripts in case of problems but obviously uses it's own user to do this. I read about --config in the source and thought, that other people would benefit from this information as well.

### CODE REVIEW

**Comment by AsamK** [comment]
Thanks, there's a typo in the PR, it's --config, not -config. The --config is already included in the first line in the usage section, although not explained.
Also the other user needs write access to the config files, to update the session store and known keys.
The recommended way for this scenario would be to have a, possibly dbus activated, signal-cli service with its own user. Then the sender doesn't need access to the config files, but can use the dbus api.

**Comment by larsborn** [comment]
all right, I fixed the type.

I didn't dare to use the dbus interface because it was marked as "experimental". Or are there plans to change this in the near future?

**Comment by AsamK** [comment]
The dbus interface is currently very minimalistic, and I'm a bit reluctant to declare it stable. However I have no immediate plans for changes to the interface.

**Comment by larsborn** [comment]
All right, good to know. I'll probably give it a try then soon!

**Pull request merged**
