### PR TITLE
Update to libsignal 2.15.3

### PR DESCRIPTION
**Pull request by signal-stickers**
Does the minimum amount of work to update to libsignal 2.15.3. Basically just assumes every SignalServiceAddress has a phone number.

~~2.15.3_unofficial_1 does not appear to be published, so this PR uses a locally-built snapshot.~~

### CODE REVIEW

**Comment by signal-stickers** [comment]
Opened issue to publish 2.15.3
https://github.com/Turasa/libsignal-service-java/issues/20

**Comment by signal-stickers** [comment]
It it makes this boring PR any more exciting, it's currently blocking:
https://github.com/signal-stickers/signal-cli/pull/1

Which adds support for uploading sticker packs :)

Sorry, there's sort of a nest of PR's, but the end goal is to update signal-cli to use libsignal 2.15.3, and afterwards we can add support for sticker pack uploads.

**Comment by signal-stickers** [comment]
Thanks for publishing 2.15.3! Updated this PR, all checks pass now.

**Comment by AsamK** [comment]
thanks!

**Pull request merged**
