### PR TITLE
fix(GraalVM): explictly declare symbols causing GraalVM compiler failure

### LINKED ISSUE #1016: v.11.x native image build fails
Latest release fails during build:

```
Fatal error: com.oracle.svm.core.util.VMError$HostedError: com.oracle.svm.core.util.VMError$HostedError: New Method or Constructor found as reachable after static analysis: public java.lang.String org.asamk.signal.manager.storage.groups.LegacyGroupStore$Storage$GroupV1$JsonRecipientAddress.number()
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:72)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:682)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.svm.core.util.VMError$HostedError: New Method or Constructor found as reachable after static analysis: public java.lang.String org.asamk.signal.manager.storage.groups.LegacyGroupStore$Storage$GroupV1$JsonRecipientAddress.number()
------------------------------------------------------------------------------------------------------------------------
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:68)
	at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionFeature.getOrCreateAccessor(ReflectionFeature.java:109)
	at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ExecutableAccessorComputer.compute(ExecutableAccessorComputer.java:50)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.computeValue(ComputedValueField.java:384)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.ComputedValueField.readValue(ComputedValueField.java:353)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.meta.ReadableJavaField.readFieldValue(ReadableJavaField.java:38)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:102)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.meta.HostedField.readValue(HostedField.java:161)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObjectToImageHeap(NativeImageHeap.java:439)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addObject(NativeImageHeap.java:295)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.processAddObjectWorklist(NativeImageHeap.java:598)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageHeap.addTrailingObjects(NativeImageHeap.java:198)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:664)
	... 4 more
```

Just tried to add the field to the reflect config, but more kept on popping up one after another. Then i started the JRE build with graalvm reflect agent (`JAVA_TOOL_OPTIONS="-agentpath:/tmp/graalvm-ce-java17-22.2.0/lib/libnative-image-agent.so=config-merge-dir=/tmp/signal-cli/graalvm-config-dir/"`) but unluckily, it did not merged anything.

### PR DESCRIPTION
**Pull request by bentolor**
I'm totally new to GraalVM, but tried to fix #1016 with try & error.

Actually I just rerun `nativeCompile` and added all public getters on claimed `record`-Classes until all went through.

This is _one_ bug on a chain of issues & bugs to get my Signal notification process back running again in Homeassistant.

@AsamK @morph027

### CODE REVIEW

**Comment by morph027** [comment]
Ah, nice, tried this too in https://github.com/AsamK/signal-cli/issues/1016 but failed to find the proper syntax 🙈

**Comment by bentolor** [comment]
@morph027 Hmpfhhh... if I'd have seen that earlier. Thanks for the pointer!

**Comment by morph027** [comment]
No, all good. Just checking the build. Mine is just an issue, this PR is better (about to run a build to verify)!

**Comment by morph027** [comment]
```
Produced artifacts:
 /tmp/signal-cli/build/native/nativeCompile/signal-cli (executable)
 /tmp/signal-cli/build/native/nativeCompile/signal-cli.build_artifacts.txt (txt)
========================================================================================================================
Finished generating 'signal-cli' in 1m 41s.
    [native-image-plugin] Native Image written to: /tmp/signal-cli/build/native/nativeCompile

BUILD SUCCESSFUL in 3m 8s
```

🎉 🥳

**Comment by AsamK** [comment]
Thanks a lot!

**Pull request merged**
