### PR TITLE
update to jdk11

### PR DESCRIPTION
**Pull request by lkwg82**
updates to latest LTS to use newer language features

### CODE REVIEW

**Comment by Trolldemorted** [comment]
This might break builds on phones running older java versions (?)

**Comment by lkwg82** [comment]
What is the use case?

**Comment by Trolldemorted** [comment]
You are right, as long as libsignal is unaffected this should be good to go

**Comment by AsamK** [comment]
yeah, let's update it, even debian stable has java 11 now.
Thanks!

**Pull request merged**
